[[WGPUNative]]
arch = "aarch64"
git-tree-sha1 = "9390c01c96258fdb8c1fdebdea3a5530777338c1"
os = "macos"

        [[WGPUNative.download]]
        sha256 = "8a91d78dc111c7a23e3fade4633bfcab288809d744b38ddab9756c0ea1c07fa9"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.aarch64-macos.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "c7cfc39a3590969c5cef703502b65868649f49ad"
os = "macos"

        [[WGPUNative.download]]
        sha256 = "c21276f62e16509d74e59659d2b790004768ef3a50961c7740ff14d8023d37c7"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.x86_64-macos.tar.gz"

[[WGPUNative]]
arch = "aarch64"
git-tree-sha1 = "d4c974d67f4a9acf69305c728a77192821745332"
os = "linux"

        [[WGPUNative.download]]
        sha256 = "d2314772dd1d8963a66f711ee28762cc9a9d6c460ba32419192a33460a6300a5"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.aarch64-linux.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "a2a6adba7711be9f0c426dd04a4938548bcb8aa2"
os = "linux"

        [[WGPUNative.download]]
        sha256 = "84dfe7078a260ae91f208b03e5cefc5a2493d6a0bba4dd04a1609a5b67f63514"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.x86_64-linux.tar.gz"

[[WGPUNative]]
arch = "aarch64"
git-tree-sha1 = "4dd276267480cf1674620162e4f765b616ae845f"
os = "windows"

        [[WGPUNative.download]]
        sha256 = "9227a3d26e0b9c91d957bb2908a2b28c02d92466818bf16c6fe9de37ae5cb842"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.aarch64-windows.tar.gz"

[[WGPUNative]]
arch = "i686"
git-tree-sha1 = "5fa54d6712d46d82ebe5976160f188a4aebce07d"
os = "windows"

        [[WGPUNative.download]]
        sha256 = "0c1ce77d5ffd10259e24af3a83a842e420d17589b9a72c56f56edec930ba341b"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.i686-windows.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "3c787f0b23e626866a950040da06eecb299068d9"
os = "windows"

        [[WGPUNative.download]]
        sha256 = "ebde3f7ff4563c799dbeaabe57b2c44c2e8fd8e9addb879be494fd6e86362652"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.x86_64-windows.tar.gz"

[[WGPUNative]]
arch = "aarch64"
git-tree-sha1 = "f712409bee9d9962c63121dda77e0c63dd77e990"
os = "ios"

        [[WGPUNative.download]]
        sha256 = "b537a58e09a4897e47a6eca006b152ad00a4078c24441e80bae0aac2878e1cd3"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.aarch64-ios.tar.gz"

[[WGPUNative]]
arch = "aarch64"
git-tree-sha1 = "c88442f37f7bd37f6adbbbd5e0cd7299fd8c4fb0"
os = "android"

        [[WGPUNative.download]]
        sha256 = "54f4f947c7776a8fbdb8b052f63ea3ef672b74d9c6d192ad46d714b21808df4a"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.aarch64-android.tar.gz"

[[WGPUNative]]
arch = "i686"
git-tree-sha1 = "3089fc0d5062a6de40a5607871a7461fa91b61de"
os = "android"

        [[WGPUNative.download]]
        sha256 = "f7e31d98fb4944ad8bb598386a13bb629a154807e9c014b1407bd072da76a30a"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.i686-android.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "d910c80f9c7fa2c02b79ec1f57328106a470465a"
os = "android"

        [[WGPUNative.download]]
        sha256 = "b9797b7073939fbba03477b0e74f28347c7b7bc7352dc5e121d5b86e55ecb1d6"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v0.1.8/WGPU.v24.0.0.1.x86_64-android.tar.gz"

