[[WGPUNative]]
arch = "arm64"
git-tree-sha1 = "cfa4499f9f1a6295e419648f5dc1ba430d8f4d8a"
os = "macos"

        [[WGPUNative.download]]
        sha256 = "3e85d282f04bfbb183dc5eab7f45126182a42dc689f1291dd53feb194d82681f"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v.0.1.3/WGPU.v0.17.2.1.arm64-macos.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "68395d26d3b3a6cfc04f28ab8e465c66509c88f2"
os = "macos"

        [[WGPUNative.download]]
        sha256 = "898721dbacbf9da77e54d0ddb8691bf74c9b6d06893dfad2141c3c49f5dab11d"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v.0.1.3/WGPU.v0.17.2.1.x86_64-macos.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "7e2229e437b23f64ff6d3533db50c3b10ade1a42"
os = "linux"

        [[WGPUNative.download]]
        sha256 = "1bf8339dec42b4708c94a3ee540f1672fc1ad81d5c2a168643514e66e976caca"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v.0.1.3/WGPU.v0.17.2.1.x86_64-linux.tar.gz"

[[WGPUNative]]
arch = "i686"
git-tree-sha1 = "6b3851e466807a5093adac0ca1bb3561f1e2d87f"
os = "windows"

        [[WGPUNative.download]]
        sha256 = "b7bd0a0d84e9ea152cac1577ded684a589b610f4603a58def1d0bfd4514825d3"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v.0.1.3/WGPU.v0.17.2.1.i686-windows.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "eb1552d6c727b018c5d88f8a194531e151fb9a1b"
os = "windows"

        [[WGPUNative.download]]
        sha256 = "61dd01d6808dad22dd08cbcf0903839ffece9e93249af56340f48b756b4454eb"
        url = "https://github.com/JuliaWGPU/WGPUNative.jl/releases/download/v.0.1.3/WGPU.v0.17.2.1.x86_64-windows.tar.gz"

