[[WGPUNative]]
arch = "arm64"
git-tree-sha1 = "9c20d51368e06226b46d99c7d909d41cc183532f"
os = "macos"

        [[WGPUNative.download]]
        sha256 = "a55d528e158f617efa1ec2edaa5d1784416a5ffe74ba607820a4461b6f6d7672"
        url = "https://github.com/dvijaha/WGPUNative.jl/releases/download/v.0.1.2/WGPU.v.0.1.2.arm64-macos.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "4c29f2fcccfddff281e71b938601ffdf5b34d56b"
os = "macos"

        [[WGPUNative.download]]
        sha256 = "c1fe27b79ffe5c9748733dd15c60aaeb89b36a83d7fa99b61b1a16eb753cf5f4"
        url = "https://github.com/dvijaha/WGPUNative.jl/releases/download/v.0.1.2/WGPU.v.0.1.2.x86_64-macos.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "5b9c3a45d72da066dc555579981e80d467436a77"
os = "linux"

        [[WGPUNative.download]]
        sha256 = "b19bc1ef1b48457b9c8cef611c77aeebf477ba03175a868e0ef47950b61847b4"
        url = "https://github.com/dvijaha/WGPUNative.jl/releases/download/v.0.1.2/WGPU.v.0.1.2.x86_64-linux.tar.gz"

[[WGPUNative]]
arch = "i686"
git-tree-sha1 = "4a70224f7639f0935327d05f07704559a19ac10a"
os = "windows"

        [[WGPUNative.download]]
        sha256 = "a6418f3d466313c037231c7d89ecc48a3dc64310924969e65a9476b2ec19b830"
        url = "https://github.com/dvijaha/WGPUNative.jl/releases/download/v.0.1.2/WGPU.v.0.1.2.i686-windows.tar.gz"

[[WGPUNative]]
arch = "x86_64"
git-tree-sha1 = "99440a5403e070add0e0a6cd9444a277df54df2b"
os = "windows"

        [[WGPUNative.download]]
        sha256 = "dc8ab6c4b3cf20c761fd5feb4804694b6d665b03fad7ceb489c6511c2aa482fb"
        url = "https://github.com/dvijaha/WGPUNative.jl/releases/download/v.0.1.2/WGPU.v.0.1.2.x86_64-windows.tar.gz"

